
library("dplyr")
library("XLConnect")
library("tidyr")
library("foreign")
#library("reshape2")
library("ggplot2")
library("ggthemes")
devtools::source_url("https://raw.githubusercontent.com/blaquans/r-notes/master/R/theme_blaquans.R")
library("stringr")
